{
  "@context": {
    "nc": "http://release.niem.gov/niem/niem-core/5.0/#",
    "j": "http://release.niem.gov/niem/domains/jxdm/7.0/#",
    "PrimaryEntity": "nc:PersonFullName",
    "Aliases": "nc:UserOnlineAliasIdentity",
    "Connections": {
      "PhoneNumber": "nc:ContactTelephoneNumber",
      "VehicleLicense": "nc:VehicleLicensePlateIdentification"
    }
  },
  "QueryID": "REQ-2026-07-20-A1",
  "TargetEntity": {
    "Aliases": ["DarkNet_Phantom"]
  }
}